name: incremental-sync-NonMember
on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 1 * * 4'  # UTC时间周四1点，对应北京时间周四凌晨9点

jobs:
  incremental-sync-NonMember:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run incremental-sync-NonMember
        run: node ./src/incremental-sync-NonMember.js
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          D1_DATABASE_ID: ${{ secrets.D1_DATABASE_ID }}
