name: incremental-sync-2025
on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 19 * * *'  # UTC时间19点，对应北京时间第二天凌晨3点

jobs:
  incremental-sync-2025:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run incremental-sync-2025 update
        run: node ./src/incremental-sync-2025.js
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          D1_DATABASE_ID: ${{ secrets.D1_DATABASE_ID }}
