name: incremental-sync-Member
on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 18 * * 3'  # UTC时间周三18点，对应北京时间周四凌晨2点

jobs:
  incremental-sync-Member:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm install
      - name: Run incremental-sync-Member
        run: node ./src/incremental-sync-Member.js
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          D1_DATABASE_ID: ${{ secrets.D1_DATABASE_ID }}
